markdown: redcarpet
highlighter: null
permalink: /:title
port:
url: federicopaini.github.io
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed